version: '3.8'

services:
  foo-bar-quix:
    build: 
      context: .
      dockerfile: Dockerfile.working
    container_name: foo-bar-quix-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./input:/app/input:ro
      - ./output:/app/output
    networks:
      - foo-bar-quix-network
    restart: unless-stopped

networks:
  foo-bar-quix-network:
    driver: bridge
